import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import { cn } from "@udecode/cn";
import "./globals.css";

import { TooltipProvider } from "@/components/plate-ui/tooltip";
import { Toaster } from "@/components/ui/toaster";

export const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Task Management System",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <TooltipProvider
          disableHoverableContent
          delayDuration={500}
          skipDelayDuration={0}
        >
          {children}
        </TooltipProvider>
        <Toaster />
      </body>
    </html>
  );
}
