export const briefList = [
    {
        id: 1,
        title: "Brief title 1",
        desc: "test desc",
        status: "assigned",
        assign: 2,
        created_at: "2023-07-12 10:42 AM",
    },
    {
        id: 2,
        title: "Brief title 2",
        desc: "test desc",
        status: "reviewed",
        assign: 2,
        created_at: "2023-07-12 10:42 AM",
    },
    {
        id: 3,
        title: "Brief title 3",
        desc: "test desc",
        status: "in progress",
        assign: 3,
        created_at: "2023-07-12 10:42 AM",
    },
    {
        id: 4,
        title: "Brief title 4",
        desc: "test desc",
        status: "assigned",
        assign: 3,
        created_at: "2023-07-12 10:42 AM",
    },
    {
        id: 5,
        title: "Brief title 5",
        desc: "test desc",
        status: "done",
        assign: 2,
        created_at: "2023-07-12 10:42 AM",
    },
];